server:
    port: 80
druid:
    name: test
    username: root
    password: toread
    # 使用druid数据源
    db-type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
    type-aliases-package: com.toread.sys.entity
    mapper-locations: classpath:mapper/*.xml
mapper:
    mappers:
        - com.toread.sys.common.mybatis.CRUDMapper
    not-empty: false
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging:
  config: classpath:logback.xml
endpoints:
  actuator:
    enabled: true